version: '3'
services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}

    ports:
      - 15432:5432

    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:6.0.6
    volumes:
      - ./redis/data:/data
    ports:
      - 6378:6379
    entrypoint: redis-server --appendonly yes

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081

volumes:
  db_data:
